// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetHistoryReply struct {
	Msgs []Message `json:"msgs"`
}

type GetHistoryReq struct {
	UserId   string `json:"userId"`
	TargetId string `json:"targetId"`
	StartSeq int64  `json:"startSeq"`
	Count    int32  `json:"count"`
}

type LoginReply struct {
	Token string `json:"token"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Message struct {
	MsgId      string `json:"msgId"`
	FromUserId string `json:"fromUserId"`
	ToUserId   string `json:"toUserId"`
	Content    string `json:"content"`
	CreateTime int64  `json:"createTime"`
}

type RegisterReply struct {
	UserId string `json:"userId"`
	Token  string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type StoreMessageRequest struct {
	Msg Message `json:"msg"`
}

type StoreMessageResponse struct {
	MsgId string `json:"msgId"`
}

type WsReq struct {
}
