// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: im.proto

package server

import (
	"context"

	"go-chat/im/im"
	"go-chat/im/internal/logic"
	"go-chat/im/internal/svc"
)

type IMServiceServer struct {
	svcCtx *svc.ServiceContext
	im.UnimplementedIMServiceServer
}

func NewIMServiceServer(svcCtx *svc.ServiceContext) *IMServiceServer {
	return &IMServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IMServiceServer) StoreMessage(ctx context.Context, in *im.StoreMessageRequest) (*im.StoreMessageResponse, error) {
	l := logic.NewStoreMessageLogic(ctx, s.svcCtx)
	return l.StoreMessage(in)
}

func (s *IMServiceServer) GetHistory(ctx context.Context, in *im.GetHistoryRequest) (*im.GetHistoryResponse, error) {
	l := logic.NewGetHistoryLogic(ctx, s.svcCtx)
	return l.GetHistory(in)
}
