// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: im.proto

package imclient

import (
	"context"

	"go-chat/im/im"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetHistoryRequest    = im.GetHistoryRequest
	GetHistoryResponse   = im.GetHistoryResponse
	Message              = im.Message
	StoreMessageRequest  = im.StoreMessageRequest
	StoreMessageResponse = im.StoreMessageResponse

	IM interface {
		StoreMessage(ctx context.Context, in *StoreMessageRequest, opts ...grpc.CallOption) (*StoreMessageResponse, error)
		GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	}

	defaultIM struct {
		cli zrpc.Client
	}
)

func NewIM(cli zrpc.Client) IM {
	return &defaultIM{
		cli: cli,
	}
}

func (m *defaultIM) StoreMessage(ctx context.Context, in *StoreMessageRequest, opts ...grpc.CallOption) (*StoreMessageResponse, error) {
	client := im.NewIMClient(m.cli.Conn())
	return client.StoreMessage(ctx, in, opts...)
}

func (m *defaultIM) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	client := im.NewIMClient(m.cli.Conn())
	return client.GetHistory(ctx, in, opts...)
}
